services:
  - type: web
    name: josaa-preference-generator
    env: python
    repo: https://github.com/JARAWA/JOSAA_preference
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
