services:
  - type: web
    name: josaa-preference-generator
    env: python
    repo: https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"